# Generated by Django 3.2.3 on 2021-06-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='staff',
            name='increment_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(blank=True, choices=[('Manager', 'Manager'), ('Hr', 'Hr'), ('Sales', 'Sales'), ('Cleaner', 'Cleaner')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='salary',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
