# Generated by Django 3.2.3 on 2021-06-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210622_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronic Accessories', 'Electronic Accessories'), ('Mobile & Tablet Accessories', 'Mobile & Tablet Accessories'), ('TV & Home Appliances', 'TV & Home Appliances'), ('Kitchenware & Dinning ', 'Kitchenware & Dinning')], max_length=200, null=True),
        ),
    ]
